apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - infra/k8s/*

build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-d2dev
  artifacts:
    # - image: asia.gcr.io/ticketing-d2dev/auth
    - image: duongtok3/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: asia.gcr.io/ticketing-d2dev/client
    - image: duongtok3/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "/**/*.js"
            dest: .

    - image: duongtok3/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: duongtok3/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: duongtok3/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
