apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - infra/k8s/*

build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-d2dev
  artifacts:
    - image: asia.gcr.io/ticketing-d2dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: asia.gcr.io/ticketing-d2dev/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
